### ISSUE TITLE
Allow running the validator against specific files

### ISSUE THREAD

**Issue by ento** [ento/elm-doc#7]
Motivation: helpful in running the validator in a git pre-commit hook without incurring significant wait.

Note: we already have `--exclude` support: which should take precedence over which?

**Comment by joneshf** [comment]
For the way I'd like to use it, specifying a file means that I want validation to run on that file no matter what other arguments there are.

Alternatively, `--exclude` could be replaced with an explicit list of files (defaulting to everything if empty)

**Comment by ento** [comment]
> I want validation to run on that file no matter what other arguments there are.

Even if the file would be excluded and not validated in CI?

**Comment by joneshf** [comment]
Sorry, can you provide an example? I don't really get it.

**Comment by joneshf** [comment]
Another alternative is to throw your hands up and say you can't have both `--include` and `--exclude`.

**Comment by ento** [comment]
Assuming the use case is running validation in a pre-commit hook:

* We want to add `Page/Home.elm`, which isn't required to have documentation according to our style guide.
* The pre-commit hook runs `elm-doc . --include ui/src/Page/Home.elm --exclude 'Page.*'`, taking the exclude option from the options file shared with the CI script.
* The hook fails because included files get validated regardless of the `--exclude` rule, and you go on to add documentation to all exposed members, even though the CI script will not run validation on the new file and won't care.

**Comment by joneshf** [comment]
Gotcha! Thanks.

Even in a case like this, I would still want it to run on the file.

What do other tools do?

**Comment by ento** [comment]
Took a look at other tools: https://gist.github.com/ento/cf5593d4fac3f72d3765b3fe2ed2a204
.. and decided to add an option to switch between the two behaviors: `--force-exclusion` (name taken from rubocop).

I agree that I'd still want it to run on the file I explicitly specify. So the current plan is

```sh
$ elm-doc . --exclude 'Page.*' # doesn't check src/Page/Home.elm
$ elm-doc . src/Page/Home.elm --exclude 'Page.*' # checks src/Page/Home.elm
$ elm-doc . src/Page/Home.elm --exclude 'Page.*' --force-exclusion # doesn't check src/Page/Home.elm
```
